version: '3'

services:
    consulserver01:
        image: consul:1.10
        container_name: consulserver01
        hostname: consulserver01
        command: ['tail', '-f', '/dev/null']
        volumes:
            - ./servers/server01:/etc/consul.d

    consulserver02:
        image: consul:1.10
        container_name: consulserver02
        hostname: consulserver02
        command: ['tail', '-f', '/dev/null']
        volumes:
            - ./servers/server02:/etc/consul.d

    consulserver03:
        image: consul:1.10
        container_name: consulserver03
        hostname: consulserver03
        command: ['tail', '-f', '/dev/null']
        volumes:
            - ./servers/server03:/etc/consul.d
    
    consulclient_01:
        image: consul:1.10
        container_name: consulclient_01
        hostname: consulclient_01
        command: ['tail', '-f', '/dev/null']
        volumes:
            - ./clients/consul_01:/etc/consul.d
    
    consulclient_02:
        image: consul:1.10
        container_name: consulclient_02
        hostname: consulclient_02
        command: ['tail', '-f', '/dev/null']
        volumes:
            - ./clients/consul_01:/etc/consul.d
